Pandas is a Python library.

Pandas is used to analyze data.*

In [ ]:
import pandas as pd
df = pd.read_csv('/kaggle/input/nyc-weather-csv/nyc_weather.csv')

In [64]:
df

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333
5,1/6/2016,33,4,35,30.50,10,4.0,0,0,NaN,259
6,1/7/2016,39,11,33,30.28,10,2.0,0,3,NaN,293
7,1/8/2016,39,29,64,30.20,10,4.0,0,8,NaN,79
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109
10,1/11/2016,33,8,37,29.92,10,NaN,0,1,NaN,289
11,1/12/2016,35,15,53,29.85,10,6.0,T,4,NaN,235
12,1/13/2016,26,4,42,29.94,10,10.0,0,0,NaN,284
13,1/14/2016,30,12,47,29.95,10,5.0,T,7,NaN,266
14,1/15/2016,43,31,62,29.82,9,5.0,T,2,NaN,101
15,1/16/2016,47,37,70,29.52,8,7.0,0.24,7,Rain,340
16,1/17/2016,36,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345
17,1/18/2016,25,6,53,29.83,9,12.0,T,2,Snow,293
18,1/19/2016,22,3,42,30.03,10,11.0,0,1,NaN,293
19,1/20/2016,32,15,49,30.13,10,6.0,0,2,NaN,302
20,1/21/2016,31,11,45,30.15,10,6.0,0,1,NaN,312
21,1/22/2016,26,6,41,30.21,9,NaN,0.01,3,Snow,34
22,1/23/2016,26,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42
23,1/24/2016,28,11,53,29.92,8,6.0,T,3,Snow,327
24,1/25/2016,34,18,54,30.25,10,3.0,0,2,NaN,286
25,1/26/2016,43,29,56,30.03,10,7.0,0,2,NaN,244
26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
27,1/28/2016,37,20,51,29.90,10,5.0,0,1,NaN,234
28,1/29/2016,36,21,50,29.58,10,8.0,0,4,NaN,298
29,1/30/2016,34,16,46,30.01,10,7.0,0,0,NaN,257
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,NaN,241

In [65]:
df.head()

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333

**What is the Maximum temperature ?**

In [66]:
df['Temperature'].max()

50

**On which dates it has rained ?**

In [67]:
df['EST'][df['Events'] == 'Rain']

8      1/9/2016
9     1/10/2016
15    1/16/2016
26    1/27/2016
Name: EST, dtype: object

**What is the average wind speed ?**

In [68]:
df.fillna(0, inplace = True)
df

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,0,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,0,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,0,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,0,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,0,333
5,1/6/2016,33,4,35,30.50,10,4.0,0,0,0,259
6,1/7/2016,39,11,33,30.28,10,2.0,0,3,0,293
7,1/8/2016,39,29,64,30.20,10,4.0,0,8,0,79
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
9,1/10/2016,50,46,71,29.59,4,0.0,1.8,7,Rain,109
10,1/11/2016,33,8,37,29.92,10,0.0,0,1,0,289
11,1/12/2016,35,15,53,29.85,10,6.0,T,4,0,235
12,1/13/2016,26,4,42,29.94,10,10.0,0,0,0,284
13,1/14/2016,30,12,47,29.95,10,5.0,T,7,0,266
14,1/15/2016,43,31,62,29.82,9,5.0,T,2,0,101
15,1/16/2016,47,37,70,29.52,8,7.0,0.24,7,Rain,340
16,1/17/2016,36,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345
17,1/18/2016,25,6,53,29.83,9,12.0,T,2,Snow,293
18,1/19/2016,22,3,42,30.03,10,11.0,0,1,0,293
19,1/20/2016,32,15,49,30.13,10,6.0,0,2,0,302
20,1/21/2016,31,11,45,30.15,10,6.0,0,1,0,312
21,1/22/2016,26,6,41,30.21,9,0.0,0.01,3,Snow,34
22,1/23/2016,26,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42
23,1/24/2016,28,11,53,29.92,8,6.0,T,3,Snow,327
24,1/25/2016,34,18,54,30.25,10,3.0,0,2,0,286
25,1/26/2016,43,29,56,30.03,10,7.0,0,2,0,244
26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
27,1/28/2016,37,20,51,29.90,10,5.0,0,1,0,234
28,1/29/2016,36,21,50,29.58,10,8.0,0,4,0,298
29,1/30/2016,34,16,46,30.01,10,7.0,0,0,0,257
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,0,241

In [69]:
df['WindSpeedMPH'].mean()

6.225806451612903